// ---------------------------------------------------------------------------
// Image Generation Providers — with automatic fallback
// ---------------------------------------------------------------------------
// Priority: ZAI (built-in) → Pollinations (free, no key) → Together (free Flux)
//           → HuggingFace (free) → fal.ai (credits)

import type { ImageProvider, ImageGenResult } from './types'

// ── ZAI SDK (built-in, always available) ──────────────────────────────────────

let zaiInstance: Awaited<ReturnType<typeof import('z-ai-web-dev-sdk').default.create>> | null = null

async function getZAI() {
  if (!zaiInstance) {
    const ZAI = (await import('z-ai-web-dev-sdk')).default
    zaiInstance = await ZAI.create()
  }
  return zaiInstance
}

export const zaiImageProvider: ImageProvider = {
  name: 'zai-sdk',
  isAvailable: () => true,
  async generate(prompt, options) {
    const zai = await getZAI()
    const enhancedPrompt = options?.style && options.style !== 'vivid'
      ? `${prompt}, ${options.style} style`
      : prompt

    const validSizes = ['1024x1024', '1344x768', '768x1344', '864x1152', '1152x864', '1440x720', '720x1440'] as const
    const size = validSizes.includes((options?.size || '') as typeof validSizes[number])
      ? (options?.size as typeof validSizes[number])
      : '1024x1024' as const

    const response = await zai.images.generations.create({
      prompt: enhancedPrompt,
      size,
    })

    if (!response.data || response.data.length === 0) {
      throw new Error('No image generated by ZAI SDK')
    }

    const imageData = response.data[0] as { base64?: string; url?: string; b64_json?: string }

    if (imageData.url) {
      return { url: imageData.url, isBase64: false, provider: 'zai-sdk' }
    }

    const b64 = imageData.b64_json || imageData.base64
    if (b64) {
      return { url: `data:image/png;base64,${b64}`, isBase64: true, provider: 'zai-sdk' }
    }

    throw new Error('No image data returned by ZAI SDK')
  },
}

// ── Pollinations AI (100% free, no API key required!) ────────────────────────

export const pollinationsProvider: ImageProvider = {
  name: 'pollinations',
  isAvailable: () => true, // Always available — no key needed
  async generate(prompt, options) {
    const width = parseInt(options?.size?.split('x')[0] || '1024')
    const height = parseInt(options?.size?.split('x')[1] || '1024')

    const encodedPrompt = encodeURIComponent(prompt)
    const url = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=${width}&height=${height}&model=flux&nologo=true`

    const res = await fetch(url)
    if (!res.ok) {
      throw new Error(`Pollinations API error: ${res.status}`)
    }

    const buffer = Buffer.from(await res.arrayBuffer())
    const base64 = buffer.toString('base64')

    return {
      url: `data:image/png;base64,${base64}`,
      isBase64: true,
      provider: 'pollinations',
      model: 'flux',
    }
  },
}

// ── Together AI (FLUX.1-schnell is FREE forever) ─────────────────────────────

export const togetherImageProvider: ImageProvider = {
  name: 'together',
  isAvailable: () => !!process.env.TOGETHER_API_KEY,
  async generate(prompt, options) {
    const res = await fetch('https://api.together.xyz/v1/images/generations', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${process.env.TOGETHER_API_KEY}`,
      },
      body: JSON.stringify({
        model: 'black-forest-labs/FLUX.1-schnell',
        prompt,
        width: parseInt(options?.size?.split('x')[0] || '1024'),
        height: parseInt(options?.size?.split('x')[1] || '1024'),
        steps: 4,
        n: 1,
      }),
    })

    if (!res.ok) {
      const err = await res.text()
      throw new Error(`Together API error ${res.status}: ${err}`)
    }

    const data = await res.json()
    const img = data.data?.[0]

    if (img?.b64_json) {
      return { url: `data:image/png;base64,${img.b64_json}`, isBase64: true, provider: 'together', model: 'flux-schnell' }
    }
    if (img?.url) {
      return { url: img.url, isBase64: false, provider: 'together', model: 'flux-schnell' }
    }

    throw new Error('No image data returned by Together API')
  },
}

// ── Hugging Face Inference API (free, many models) ──────────────────────────

export const huggingfaceImageProvider: ImageProvider = {
  name: 'huggingface',
  isAvailable: () => !!process.env.HF_TOKEN,
  async generate(prompt, _options) {
    const model = 'black-forest-labs/FLUX.1-dev'
    const res = await fetch(
      `https://api-inference.huggingface.co/models/${model}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${process.env.HF_TOKEN}`,
        },
        body: JSON.stringify({ inputs: prompt }),
      },
    )

    if (!res.ok) {
      const err = await res.text()
      throw new Error(`HuggingFace API error ${res.status}: ${err}`)
    }

    const buffer = Buffer.from(await res.arrayBuffer())
    const base64 = buffer.toString('base64')

    return {
      url: `data:image/png;base64,${base64}`,
      isBase64: true,
      provider: 'huggingface',
      model: 'flux-dev',
    }
  },
}

// ── fal.ai (fast, TypeScript SDK, $10 free credits) ─────────────────────────

export const falImageProvider: ImageProvider = {
  name: 'fal-ai',
  isAvailable: () => !!process.env.FAL_API_KEY,
  async generate(prompt, options) {
    const res = await fetch('https://queue.fal.run/fal-ai/flux/schnell', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Key ${process.env.FAL_API_KEY}`,
      },
      body: JSON.stringify({
        prompt,
        image_size: options?.size || 'square_hd',
        num_inference_steps: 4,
      }),
    })

    if (!res.ok) {
      const err = await res.text()
      throw new Error(`fal.ai API error ${res.status}: ${err}`)
    }

    const data = await res.json()
    // fal.ai returns { images: [{ url: "..." }] }
    const imageUrl = data.images?.[0]?.url

    if (!imageUrl) {
      throw new Error('No image URL returned by fal.ai')
    }

    // Download the image and convert to base64 for consistency
    const imgRes = await fetch(imageUrl)
    if (!imgRes.ok) throw new Error('Failed to download fal.ai image')
    const buffer = Buffer.from(await imgRes.arrayBuffer())
    const base64 = buffer.toString('base64')

    return {
      url: `data:image/png;base64,${base64}`,
      isBase64: true,
      provider: 'fal-ai',
      model: 'flux-schnell',
    }
  },
}

// ── Ordered provider list for fallback ───────────────────────────────────────

export const imageProviders: ImageProvider[] = [
  zaiImageProvider,
  pollinationsProvider,
  togetherImageProvider,
  huggingfaceImageProvider,
  falImageProvider,
]
